version: "3.9"

services:
  db1:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db1_data:/var/lib/postgresql/data
      - ./init_db/init_db1.sql:/docker-entrypoint-initdb.d/init_db1.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  db2:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db2_data:/var/lib/postgresql/data
      - ./init_db/init_db2.sql:/docker-entrypoint-initdb.d/init_db2.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy

volumes:
  db1_data:
  db2_data: